Update to the latest script, github action

diff --git a/scripts/generate-patch b/scripts/generate-patch
--- a/scripts/generate-patch
+++ b/scripts/generate-patch
@@ -11,31 +11,17 @@ function remove_timestamp_from_diff {
 	time="[[:digit:]]\{2\}:[[:digit:]]\{2\}:[[:digit:]]\{2\}.[[:digit:]]\{9\}"
 	timezone="[-\+][[:digit:]]\{4\}"
 	timestamp_format="${date}[[:space:]]${time}[[:space:]]${timezone}"
-	sed -i '' "s/\(${prefix} ${filename_format}\)[[:space:]]${timestamp_format}/\1/g" ${f}/$(basename -- ${f}).patch
+	sed -i.bak "s/\(${prefix} ${filename_format}\)[[:space:]]${timestamp_format}/\1/g" ${f}/$(basename -- ${f}).patch
+	rm ${f}/$(basename -- ${f}).patch.bak
 }
-
-function revert_crd_changes {
-	if [[ -z $1 ]]; then
-		echo "No directory provided to revert charts-crd changes within"
-		exit 1
-	fi
-	# Move charts-crd/templates back into charts/crd/
-	mkdir -p ${f}/charts/crds/
-	mv ${f}/charts-crd/templates/* ${f}/charts/crds/
-	# Remove the validate-install-${name}-crd.yaml
-	name=$(cat ${f}/charts/Chart.yaml | yq r - 'name')
-	rm ${f}/charts/templates/validate-install-${name}-crd.yaml
-	# Remove additional annotations added to original chart
-	yq d -i ${f}/charts/Chart.yaml "annotations[catalog.cattle.io/auto-install-gvr]"
-	# Remove charts-crd
-	rm -rf ${f}/charts-crd
-}
-
 
 for f in packages/*; do
-  if [[ -f ${f}/package.yaml ]]; then
-  	if [[ -z $CHART || $CHART == $(basename -- ${f}) ]]; then
+	if [[ -f ${f}/package.yaml ]]; then
+		if [[ -z $CHART || $CHART == $(basename -- ${f}) ]]; then
 			url=$(cat ${f}/package.yaml | yq r - url)
+			if [[ -z ${url} ]]; then
+				continue
+			fi
 			subdirectory=$(cat ${f}/package.yaml | yq r - subdirectory)
 			type=$(cat ${f}/package.yaml | yq r - type)
 			commit=$(cat ${f}/package.yaml | yq r - commit)
@@ -57,13 +43,44 @@ for f in packages/*; do
 				mkdir -p ${f}/charts-original
 				curl -sLf ${url} | tar xvzf - -C ${f}/charts-original --strip ${fields} ${subdirectory} > /dev/null 2>&1
 			fi
+			if [[ -f ${f}/charts/requirements.yaml ]]; then
+				i=0
+				while ! [[ -z $(yq r ${f}/charts/requirements.yaml "dependencies[${i}]") ]]; do
+					subchart=$(yq r ${f}/charts/requirements.yaml "dependencies[${i}].name" | head -n 1)
+					version=$(yq r ${f}/charts/requirements.yaml "dependencies[${i}].version" | head -n 1)
+					helm_repo=$(yq r ${f}/charts/requirements.yaml "dependencies[${i}].repository" | head -n 1)
+					# Remove trailing slash
+					[[ ${helm_repo} == */ ]] && helm_repo=${helm_repo%/}
+					if [[ ${helm_repo} == file://* ]] || [[ ! ${version} =~ ^[0-9\.]+$ ]]; then
+						# Subchart is tracked locally; patches will not be tracked
+						rm -rf ${f}/charts-original/charts/${subchart}
+						((i=i+1))
+						continue
+					fi
+					# Subchart is tracked in remote Helm repo with a fixed version number; we grab the download URL and get the local chart archive
+					download_url=$(curl -sLf ${helm_repo}/index.yaml | cat | yq r - "entries.${subchart}.(version == ${version}).urls[0]")
+					if [[ -z ${download_url} ]]; then
+						echo "Failed to get download URL for ${subchart} at version ${version} from index.yaml at ${helm_repo}"
+						exit 1
+					fi
+					echo "Comparing current changes to ${subchart}-${version} against upstream found at ${download_url}"
+					curl -sLf ${download_url} | tar xvzf - -C ${f}/charts-original/charts > /dev/null 2>&1
+					((i=i+1))
+				done
+			fi
 			if [[ -d ${f}/charts ]]; then
 				split_crds=$(cat ${f}/package.yaml | yq r - generateCRDChart.enabled)
 				if [[ "${split_crds}" == "true" ]]; then
-					revert_crd_changes ${f}
+					./scripts/clean-crds ${f}
 				fi
 				diff -x *.tgz -x *.lock -uNr ${f}/charts-original ${f}/charts > ${f}/$(basename -- ${f}).patch || true
-				remove_timestamp_from_diff
+				if ! [[ -s ${f}/$(basename -- ${f}).patch ]]; then
+					# If no changes exist in patch then remove it
+					rm ${f}/$(basename -- ${f}).patch
+				fi
+				if [[ -f ${f}/$(basename -- ${f}).patch ]]; then
+					remove_timestamp_from_diff
+				fi
 				if [[ "${split_crds}" == "true" ]]; then
 					./scripts/prepare-crds ${f}
 				fi
